SERVICE_AUTH_HEADER = "X-Ontos-Service-Auth"
USER_ID_HEADER = "X-Ontogit-User"
SERVICE_AUTH_ENV = "ONTOS_SERVICE_AUTH_SECRET"
JWT_HEADER = "X-Ontogit-Auth"

DAILY_TOKEN_LIMIT_ENV = "ONTOGIT_DAILY_TOKEN_LIMIT"
DAILY_REQUEST_LIMIT_ENV = "ONTOGIT_DAILY_REQUEST_LIMIT"
LIMIT_MODE_ENV = "ONTOGIT_LIMIT_MODE"
ADMIN_USERS_ENV = "ONTOGIT_ADMIN_USERS"

WARN_SERVICE_AUTH = "OntoGit memory-service auth missing/mismatch"
WARN_USER_ID_MISSING = "User id not propagated; usage will be aggregated"
WARN_QUOTA_EXCEEDED = "Quota exceeded"
WARN_RATE_LIMITED = "Rate limited"
